version: '3'
services:
  backend-panda:
    build:
      context: ./backend-panda
    ports:
      - 3000:3000
    tty: true
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend-panda
